#!/bin/csh

if($#argv == 0) then
  echo
  cat ./pdata/1/title
  echo
  awk '/\$NS/ {print "Scans: " $2}' acqus
  awk '/\$RG/ {print "Receiver gain: " $2}' acqus
  if (-e acqu2s) then
    awk '/\$TD/ {print "Indirect increments: " $2}' acqu2s
  endif
  if (-e acqu3s) then
    awk '/\$TD/ {print "Indirect increments (2): " $2}' acqu3s
  endif
  echo
  awk '/\$BF1/ {print "BF1: " $2}' acqus
  awk '/\$SFO1/ {print "SFO1: " $2}' acqus
  awk '/\$O1/ {print "O1: " $2}' acqus
  if (-e acqu2s) then
    echo
    awk '/\$BF3/ {print "BF3: " $2}' acqus
    awk '/\$SFO3/ {print "SFO3: " $2}' acqus
    awk '/\$O3/ {print "O3: " $2}' acqus
  endif
  if (-e acqu3s) then
    echo
    awk '/\$BF1/ {print "BF2: " $2}' acqu3s
    awk '/\$SFO1/ {print "SFO2: " $2}' acqu3s
    awk '/\$O1/ {print "O2: " $2}' acqu3s
  endif
  echo
endif

if($#argv == 1) then
  echo
       cat ./$1/pdata/1/title
  echo
  awk '/\$NS/ {print "Scans: " $2}' ./$1/acqus
  awk '/\$RG/ {print "Receiver gain: " $2}' ./$1/acqus
  if (-e ./$1/acqu2s) then
    awk '/\$TD/ {print "Indirect increments: " $2}' ./$1/acqu2s
  endif
  if (-e ./$1/acqu3s) then
    awk '/\$TD/ {print "Indirect increments (2): " $2}' ./$1/acqu3s
  endif
  echo
  awk '/\$BF1/ {print "BF1: " $2}' ./$1/acqus
  awk '/\$SFO1/ {print "SFO1: " $2}' ./$1/acqus
  awk '/\$O1/ {print "O1: " $2}' ./$1/acqus
  if (-e ./$1/acqu2s) then
    echo
    awk '/\$BF3/ {print "BF3: " $2}' ./$1/acqus
    awk '/\$SFO3/ {print "SFO3: " $2}' ./$1/acqus
    awk '/\$O3/ {print "O3: " $2}' ./$1/acqus
  endif
  if (-e ./$1/acqu3s) then
    echo
    awk '/\$BF1/ {print "BF2: " $2}' ./$1/acqu3s
    awk '/\$SFO1/ {print "SFO2: " $2}' ./$1/acqu3s
    awk '/\$O1/ {print "O2: " $2}' ./$1/acqu3s
  endif
  echo
endif
